facturacion_app/config/routes.rb
Rails.application.routes.draw do
  
  get 'students/index'
  resources :students
  
  get 'providers/index'
  resources :providers
  get "/providers/:provider_id/new_bill" => "provider_bills#new"

  
  get 'clients/index'
  resources :clients
  get "/clients/:client_id/services/:service_id/new_bill" => "bills#new"
  get "/clients/:client_id/services" => "services#bindex"
  
  resources :services

  resources :provider_bills
  get '/provider_bills/:provider_id/transactions' => 'transactions#new'

  resources :bills
  get '/bills/:bill_id/transactions' => 'transactions#new'

  resources :transactions


end

facturacion_app/app/models/provider.rb
class Provider < ActiveRecord::Base
	validates :name, presence: true, length: {minimum: 5,maximum: 40}
	validates :rif, presence: true, length: {in: 10..15}, uniqueness: true
	validates :phone, presence: true, length: {in: 7..11}
	validates :email, presence: true, length: {in: 5..30}, uniqueness: true

end

facturacion_app/app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  def index
    @providers = Provider.all
  end
  def new
    @provider = Provider.new
  end
  def create
    @provider = Provider.new(permit_params)
    if @provider.save
      redirect_to providers_path
    else
      render 'new'
    end
  end
  def edit
    @provider = Provider.find(params[:id])
  end
  def update
    @provider = Provider.find(params[:id])
    if @provider.update(permit_params)
      redirect_to providers_path
    else
      render 'edit'
    end
  end
  def destroy
    @provider = Provider.find(params[:id])
    if @provider.delete
      redirect_to providers_path
    end
  end
  private
    def permit_params
      params.require(:provider).permit(:name, :rif, :phone)
    end
end

facturacion_app/app/helpers/providers_helper.rb
module ProvidersHelper
end

facturacion_app/app/views/providers/edit.html.erb
<div class="row">
	<div class="container">
		<div class="col-md-offset-2 col-md-8">    
			<div class="panel panel-primary">
				<div class="panel-heading"><i class="fa fa-users"></i> Edit Provider</div>
				<div class="panel-body">
<%= semantic_form_for @provider do |f| %>
  <%= f.input :name %>
  <%= f.input :phone %>
  <%= f.input :email %>
  <%= f.input :adress %>
<%= f.action :submit, :label => "Update", :button_html => { :class => "btn btn-primary"} %>
<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

facturacion_app/app/views/providers/index.html.erb
<div class="row">
  <div class="container">
    <div class="col-md-12">    
      <div class="panel panel-primary">
        <div class="panel-heading"><i class="fa fa-users"></i> Provider List</div>
        <div class="panel-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Name</th>
                <th>Rif</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Address</th>
              </tr>
            </thead>
            <tbody>
              <% @providers.each do |provider| %>
              <tr>
                <td><%= provider.name %></td>
                <td><%= provider.rif %></td>
                <td><%= provider.phone %></td>
                <td><%= provider.email %></td>
                <td><%= provider.adress %></td>
                <td><%= link_to "New Bill", 'http://localhost:3000/providers/'+provider.id.to_s+'/new_bill' , class:"btn btn-warning" %></td>
                <td><%= link_to "Edit", edit_provider_path(provider), class:"btn btn-info" %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
          <%= link_to "Create Provider", new_provider_path, class:"btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
</div>

facturacion_app/app/views/providers/new.html.erb
<div class="row">
	<div class="container">
		<div class="col-md-offset-2 col-md-8">    
			<div class="panel panel-primary">
				<div class="panel-heading"><i class="fa fa-building-o"></i> New Provider</div>
				<div class="panel-body">
					<%= semantic_form_for @provider do |f| %>
					<%= f.input :name, placeholder: "Insert name" %>
					<%= f.input :rif, placeholder: "Insert Fiscal Information Registration" %>
					<%= f.input :phone,placeholder: "Insert phone" %>
					<%= f.input :email, placeholder: "Insert email" %>
					<%= f.input :adress,placeholder: "Insert addres" %>
					<%= f.action :submit, :label => "Submit", :button_html => { :class => "btn btn-primary"} %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>