facturacion_app/config/routes.rb
Rails.application.routes.draw do
  
  get 'students/index'
  resources :students
  
  get 'providers/index'
  resources :providers
  get "/providers/:provider_id/new_bill" => "provider_bills#new"

  
  get 'clients/index'
  resources :clients
  get "/clients/:client_id/services/:service_id/new_bill" => "bills#new"
  get "/clients/:client_id/services" => "services#bindex"
  
  resources :services

  resources :provider_bills
  get '/provider_bills/:provider_id/transactions' => 'transactions#new'

  resources :bills
  get '/bills/:bill_id/transactions' => 'transactions#new'

  resources :transactions


end

facturacion_app/app/models/student.rb
class Student < ActiveRecord::Base
  enum active: {active: 1, inactive: 0}

  validates :name, presence: true, length: {minimum: 3, maximum: 15}
  validates :l_name, presence: true, length: {minimum: 3, maximum: 15}
  validates :identification, presence: true, length: {minimum: 3, maximum: 11}, uniqueness: true
  validates :phone, length: {in: 7..11}, presence: true, uniqueness: true
  validates :email, presence: true, length: {in: 5..30}, uniqueness: true

  belongs_to :client
end

facturacion_app/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end
  def new
    @student = Student.new
  end
  def create
    @student = Student.new(permit_params)
    if @student.save
      redirect_to students_path
    else
      render 'new'
    end
  end
  def edit
    @student = Student.find(params[:id])
  end
  def update
    @student = Student.find(params[:id])
    if @student.update(permit_params)
      redirect_to students_path
    else
      render 'edit'
    end
  end
  def destroy
    @student = Student.find(params[:id])
    if @student.delete
      redirect_to students_path
    end
  end
  private
    def permit_params
      params.require(:student).permit(:name, :rif, :phone)
    end
end

facturacion_app/app/helpers/students_helper.rb
module StudentsHelper
end

facturacion_app/app/views/students/edit.html.erb
<h1>Edit Student</h1>

<%= semantic_form_for @student do |f| %>
  <%= f.input :name %>
  <%= f.input :phone %>
  <%= f.input :email %>
  <%= f.input :adress %>
<%= f.action :submit, :label => "Update", :button_html => { :class => "btn btn-primary"} %>
<% end %>

facturacion_app/app/views/students/index.html.erb
<div class="row">
  <div class="container">
    <div class="col-md-12">    
      <div class="panel panel-primary">
        <div class="panel-heading"><i class="fa fa-users"></i> Provider List</div>
        <div class="panel-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Name</th>
                <th>Rif</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Address</th>
                <th>Status</th>
                <th>Client</th>
                <th>Edit</th>
              </tr>
            </thead>
            <tbody>
              <% @students.each do |student| %>
              <tr>
                <td><%= student.name %></td>
                <td><%= student.identification %></td>
                <td><%= student.phone %></td>
                <td><%= student.email %></td>
                <td><%= student.adress %></td>
                <td><%= student.active %></td>
                <td><%= link_to "Client", client_path(student.client_id), class:"btn btn-default" %></td>
                <td><%= link_to "Edit", edit_student_path(student), class:"btn btn-default" %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
          <%= link_to "Create Student", new_student_path, class:"btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
</div>

facturacion_app/app/views/students/new.html.erb
<h1>New Student</h1>

<%= semantic_form_for @student do |f| %>
<%= f.input :name %>
<%= f.input :phone %>
<%= f.input :email %>
<%= f.input :adress %>
<%= f.action :submit, :label => "Submit", :button_html => { :class => "btn btn-primary"} %>
<% end %>