facturacion_app/config/routes.rb
Rails.application.routes.draw do
  
  get 'students/index'
  resources :students
  
  get 'providers/index'
  resources :providers
  get "/providers/:provider_id/new_bill" => "provider_bills#new"

  
  get 'clients/index'
  resources :clients
  get "/clients/:client_id/services/:service_id/new_bill" => "bills#new"
  get "/clients/:client_id/services" => "services#bindex"
  
  resources :services

  resources :provider_bills
  get '/provider_bills/:provider_id/transactions' => 'transactions#new'

  resources :bills
  get '/bills/:bill_id/transactions' => 'transactions#new'

  resources :transactions


end

facturacion_app/app/models/client.rb
class Client < ActiveRecord::Base
	validates :name, presence: true, length: {minimum: 3, maximum: 40}
	validates :rif, presence: true, length: {minimum: 3, maximum: 15}, uniqueness: true
	validates :phone, presence: true, length: {minimum: 7, maximum: 11}
	validates :email, presence: true, length: {minimum: 5, maximum: 30}, uniqueness: true
end

facturacion_app/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end
  def new
    @client = Client.new
  end
  def create
    @client = Client.new(permit_params)
    if @client.save
      redirect_to clients_path
    else
      render 'new'
    end
  end
  def edit
    @client = Client.find(params[:id])
  end
  def update
    @client = Client.find(params[:id])
    if @client.update(permit_params)
      redirect_to clients_path
    else
      render 'edit'
    end
  end
  def destroy
    @client = Client.find(params[:id])
    if @client.delete
      redirect_to clients_path
    end
  end
  private
    def permit_params
      params.require(:client).permit(:name, :rif, :phone)
    end
end

facturacion_app/app/helpers/clients_helper.rb
module ClientsHelper
end

facturacion_app/app/views/clients/edit.html.erb
<div class="row">
	<div class="container">
		<div class="col-md-offset-2 col-md-8">    
			<div class="panel panel-primary">
				<div class="panel-heading"><i class="fa fa-pencil-square-o"></i> Edit Client</div>
				<div class="panel-body">
					<%= semantic_form_for @client do |f| %>
					<%= f.input :name %>
					<%= f.input :phone %>
					<%= f.input :email %>
					<%= f.input :address %>
					<%= f.action :submit, :label => "Update", :button_html => { :class => "btn btn-primary"} %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

facturacion_app/app/views/clients/index.html.erb
<div class="row">
  <div class="container">
    <div class="col-md-12">    
      <div class="panel panel-primary">
        <div class="panel-heading"><i class="fa fa-users"></i> Clients List</div>
        <div class="panel-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Name</th>
                <th>Rif</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Address</th>
              </tr>
            </thead>
            <tbody>
              <% @clients.each do |client| %>
              <tr>
                <td><%= client.name %></td>
                <td><%= client.rif %></td>
                <td><%= client.phone %></td>
                <td><%= client.email %></td>
                <td><%= client.address %></td>
                <td><%= link_to "New Bill", 'http://localhost:3000/clients/'+client.id.to_s+'/services', class:"btn btn-warning" %></td>
                <td><%= link_to "Edit", edit_client_path(client), class:"btn btn-info" %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
          <%= link_to "Create Client", new_client_path, class: "btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
</div>

facturacion_app/app/views/clients/new.html.erb
<div class="row">
	<div class="container">
		<div class="col-md-offset-2 col-md-8">    
			<div class="panel panel-primary">
				<div class="panel-heading"><i class="fa fa-plus-square"></i> New Client</div>
				<div class="panel-body">
					<%= semantic_form_for @client do |f| %>
					<%= f.input :name, placeholder: "Insert name" %>
					<%= f.input :rif, placeholder: "Insert Fiscal Information Registration" %>
					<%= f.input :phone, placeholder: "Insert Phone" %>
					<%= f.input :email, placeholder: "Insert name" %>
					<%= f.input :address, placeholder: "Insert Address" %>
					<%= f.action :submit, :label => "Submit", :button_html => { :class => "btn btn-primary"} %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>