facturacion_app/config/routes.rb
Rails.application.routes.draw do
  
  get 'students/index'
  resources :students
  
  get 'providers/index'
  resources :providers
  get "/providers/:provider_id/new_bill" => "provider_bills#new"

  
  get 'clients/index'
  resources :clients
  get "/clients/:client_id/services/:service_id/new_bill" => "bills#new"
  get "/clients/:client_id/services" => "services#bindex"
  
  resources :services

  resources :provider_bills
  get '/provider_bills/:provider_id/transactions' => 'transactions#new'

  resources :bills
  get '/bills/:bill_id/transactions' => 'transactions#new'

  resources :transactions


end

facturacion_app/app/models/service.rb
class Service < ActiveRecord::Base
	validates :name, length: {in: 5..30}, presence: true
	validates :details, presence: true
	validates :amount, numericality: true, presence: true
end

facturacion_app/app/controllers/services_controller.rb
class ServicesController < ApplicationController
	def index
		@services = Service.all
	end
	def bindex
		@services = Service.all
		@aux = params[:client_id] 
	end
	def new
		@service = Service.new
	end
	def create
		@service = Service.new(permit_params)
		if @service.save
			redirect_to services_path
		else
			render 'new'
		end
	end
	def edit
		@service = Service.find(params[:id])
	end
	def update
		@service = Service.find(params[:id])
		if @student.update(permit_params)
			redirect_to students_path
		else
			render 'new'
		end
	end
	def destroy
		@service = Service.find(params[:id])
		if @student.delete
			redirect_to services_path
		end
	end
	private
	def permit_params
		params.require(:service).permit(:name, :details, :amount)
	end
end

facturacion_app/app/helpers/services_helper.rb
module ServicesHelper
end

facturacion_app/app/views/services/bindex.html.erb
<div class="row">
  <div class="container">
    <div class="col-md-12">    
      <div class="panel panel-primary">
        <div class="panel-heading"><h3><i class="fa fa-users"></i> Select Services</h3></div>
        <div class="panel-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Name</th>
                <th>Details</th>
                <th>Amount</th>
              </tr>
            </thead>
            <tbody>
              <% @services.each do |ser| %>
              <tr>
                <td><%= ser.name %></td>
                <td><%= ser.details %></td>
                <td><%= ser.amount %></td>
                <td><%= link_to "select",'http://localhost:3000/clients/'+params[:client_id].to_s+'/services/'+ ser.id.to_s+'/new_bill', class:"btn btn-info" %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
          <%= link_to "Create Service", new_service_path, class:"btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
</div>

facturacion_app/app/views/services/edit.html.erb
<div class="row">
	<div class="container">
		<div class="col-md-offset-2 col-md-8">    
			<div class="panel panel-primary">
				<div class="panel-heading"><i class="fa fa-pencil-square-o"></i> Edit Service</div>
				<div class="panel-body">
					<%= semantic_form_for @service do |f| %>
					<%= f.input :name %>
					<%= f.input :details %>
					<%= f.input :amount %>
					<%= f.action :submit, :label => "Update", :button_html => { :class => "btn btn-primary"} %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

facturacion_app/app/views/services/index.html.erb
<div class="row">
  <div class="container">
    <div class="col-md-12">    
      <div class="panel panel-primary">
        <div class="panel-heading"><i class="fa fa-users"></i> Serveices List</div>
        <div class="panel-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Name</th>
                <th>Details</th>
                <th>Amount</th>
              </tr>
            </thead>
            <tbody>
              <% @services.each do |ser| %>
              <tr>
                <td><%= ser.name %></td>
                <td><%= ser.details %></td>
                <td><%= ser.amount %></td>
                <td><%= link_to "Edit", edit_service_path(ser), class:"btn btn-info" %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
          <%= link_to "Create Service", new_service_path, class:"btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
</div>

facturacion_app/app/views/services/new.html.erb
<div class="row">
	<div class="container">
		<div class="col-md-offset-2 col-md-8">    
			<div class="panel panel-primary">
				<div class="panel-heading"><i class="fa fa-plus-square"></i> New Service</div>
				<div class="panel-body">
					<%= semantic_form_for @service do |f| %>
					<%= f.input :name %>
					<%= f.input :details %>
					<%= f.input :amount %>
					<%= f.action :submit, :label => "Submit", :button_html => { :class => "btn btn-primary"} %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>